@startuml ユースケース図
title atte ユースケース図

!theme cloudscape-design

left to right direction

skinparam actorstyle awesome

actor 社員 #LightGreen

package "社員入力システム" {
    usecase 勤務終了
    usecase 勤務開始
    usecase 会員登録
    usecase 休憩終了
    usecase 休憩開始
    usecase ログイン
    usecase 日付別勤怠情報
    }
社員 --> 社員入力システム

@enduml
